### ISSUE TITLE
No music and levels "freezing"/ stopping in place.

### ISSUE THREAD

**Issue by CrimsonFork** [geode-sdk/geode#1007]
### Geode Issue

- [X] I confirm that this bug is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

3.2.0

### Mods Installed

None.

### Expected Behavior

Normal gameplay.

### Actual Behavior

The game has a tendency to "freeze" at certain parts early into the levels, sometimes at the very first frame, where all motion stops but certain animations (monsters, cube ground particles) keep playing. While in this state, shaders break if the game becomes unfocused by pulling down the notification tray. Gameplay resumes if paused and unpaused, unless it happens at the first frame, in which case it stays frozen.

Launching the game for the second+ time has all audio disabled, to the same effect as all the sliders being all the way to the left. Readjusting the sliders doesn't help.

Here's a video of the issues occurring. https://youtu.be/IiEjp3eZoGc

Application log (sharing it crashed the launcher BTW):
```
2024-07-19T19:40:26.283439418 [I/Geode]: 19:40:26 INFO  [Thread #26678] [Geode]: Saving mod data...
2024-07-19T19:40:26.287785122 [I/Geode]: 19:40:26 INFO  [Thread #26678] [Geode]:   Took 0.004s
2024-07-19T19:40:29.677520800 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:40:29.677568041 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:40:29.677580818 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: OFF with frames = 0
2024-07-19T19:40:29.677590421 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:40:29.677600594 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:40:29.725225390 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#10 ----------------
2024-07-19T19:40:29.909791593 [I/fmod]: FMOD::supportsLowLatency : Low latency = true, Pro Audio = true, Bluetooth On = false, Acceptable Block Size = true (128)
2024-07-19T19:40:29.909899951 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:40:29.909928800 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:40:29.909941129 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:40:29.909952238 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:40:29.909962898 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:40:29.940201790 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#11 ----------------
2024-07-19T19:40:30.065370898 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:40:30.065471240 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:40:30.065496102 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:40:30.065513517 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:40:30.065531258 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:40:30.089958870 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#12 ----------------
2024-07-19T19:40:30.176269661 [I/Choreographer]: Skipped 56 frames!  The application may be doing too much work on its main thread.
2024-07-19T19:40:30.187424935 [I/ImeTracker]: com.geode.launcher:887fc9e0: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
2024-07-19T19:40:30.187500130 [I/ImeTracker]: com.geode.launcher:887fc9e0: onFailed at PHASE_CLIENT_VIEW_SERVED
2024-07-19T19:40:30.244823169 [I/ImeTracker]: com.geode.launcher:2bd86f81: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
2024-07-19T19:40:36.906154308 [W/Choreographer]: Frame time is 0.24464 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:42:55.638934731 [W/Choreographer]: Frame time is 0.008574 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:42:58.461421508 [I/Geode]: 19:42:58 INFO  [Thread #26678] [Geode]: Saving mod data...
2024-07-19T19:42:58.466598469 [I/Geode]: 19:42:58 INFO  [Thread #26678] [Geode]:   Took 0.005s
2024-07-19T19:42:59.110544555 [I/Process]: Sending signal. PID: 26596 SIG: 9
2024-07-19T19:43:00.203931966 [I/.geode.launcher]: Using CollectorTypeCMC GC.
2024-07-19T19:43:00.207463460 [E/.geode.launcher]: Not starting debugger since process cannot load the jdwp agent.
2024-07-19T19:43:00.319860473 [W/Choreographer]: Frame time is 0.170701 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:00.398505615 [W/Choreographer]: Frame time is 0.095028 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:00.476887248 [W/Choreographer]: Frame time is 0.265811 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:00.572972290 [W/Choreographer]: Frame time is 0.208264 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:03.882792034 [W/.geode.launcher]: Missing inline cache for boolean G.K.h(androidx.compose.ui.node.a)
2024-07-19T19:43:13.604988694 [W/Choreographer]: Frame time is 0.165766 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:46.482540183 [I/.geode.launcher]: Background concurrent mark compact GC freed 24MB AllocSpace bytes, 0(0B) LOS objects, 82% free, 5219KB/29MB, paused 2.427ms,6.301ms total 103.743ms
2024-07-19T19:43:53.892346136 [W/Choreographer]: Frame time is 0.139771 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:53.953566758 [W/Choreographer]: Frame time is 0.033748 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:43:53.964026475 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@76851e0
2024-07-19T19:43:53.971016994 [W/Choreographer]: Frame time is 0.051878 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:09.129476921 [W/WindowOnBackDispatcher]: OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2024-07-19T19:44:10.015955519 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@9fbde80
2024-07-19T19:44:12.179545771 [W/WindowOnBackDispatcher]: OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2024-07-19T19:44:12.231492873 [W/Choreographer]: Frame time is 0.044603 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:12.240221999 [W/Choreographer]: Frame time is 0.007018 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:13.926291540 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@c515d7f
2024-07-19T19:44:16.282467648 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@c323d7b
2024-07-19T19:44:16.961606971 [W/Choreographer]: Frame time is 0.100504 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:17.023928301 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@8987708
2024-07-19T19:44:17.031480099 [W/Choreographer]: Frame time is 0.056113 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:17.040242388 [W/Choreographer]: Frame time is 0.034465 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:18.435608152 [W/.geode.launcher]: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
2024-07-19T19:44:18.435713173 [W/.geode.launcher]: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2024-07-19T19:44:18.435741981 [W/.geode.launcher]: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2024-07-19T19:44:18.484848223 [W/GeodeLauncher-fix]: failed to read symbol file at /storage/emulated/0/Android/media/com.geode.launcher/exception_symbols.txt
2024-07-19T19:44:18.508721718 [I/System.out]: Loading Geode from Geode.android64.so
2024-07-19T19:44:18.502 [W/.geode.launcher]: type=1400 audit(0.0:38609): avc:  granted  { execute } for  path="/data/data/com.geode.launcher/files/copied/Geode.so" dev="dm-51" ino=27166 scontext=u:r:untrusted_app:s0:c7,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c7,c257,c512,c768 tclass=file app=com.geode.launcher
2024-07-19T19:44:18.554584429 [I/Geode]: 19:44:18 INFO  [Main] [Geode]: Running Geode v3.2.0 in Geometry Dash v2.206 on Android64
2024-07-19T19:44:18.554636960 [I/Geode]: 19:44:18 INFO  [Main] [Geode]: Setting up internal mod
2024-07-19T19:44:18.565971596 [I/Geode]: 19:44:18 INFO  [Main] [Geode]: Setting up loader
2024-07-19T19:44:18.606364337 [I/Geode]: 19:44:18 INFO  [Main] [Geode]:   Refreshing mod graph
2024-07-19T19:44:18.607146075 [I/Geode]: 19:44:18 INFO  [Main] [Geode]:     Took 0s. Continuing next frame...
2024-07-19T19:44:18.607167437 [I/Geode]: 19:44:18 INFO  [Main] [Geode]: Starting loader update check
2024-07-19T19:44:18.607318723 [I/Geode]: 19:44:18 INFO  [Main] [Geode]: Entry took 0.052s
2024-07-19T19:44:18.660726153 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:18.660765256 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:18.660768593 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: OFF with frames = 0
2024-07-19T19:44:18.660770912 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:18.660773353 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:18.675492877 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
2024-07-19T19:44:18.805781207 [I/fmod]: FMOD::supportsLowLatency : Low latency = true, Pro Audio = true, Bluetooth On = false, Acceptable Block Size = true (128)
2024-07-19T19:44:18.805812172 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:18.805821083 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:18.805824582 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:44:18.805827919 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:18.805831337 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:18.817132566 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#2 ----------------
2024-07-19T19:44:18.941582395 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:18.941608111 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:18.941613523 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:44:18.941616615 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:18.941619423 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:18.954812213 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#3 ----------------
2024-07-19T19:44:19.002804848 [I/Geode]: 19:44:19 INFO  [Thread #27570] [Geode]: Continuing mod graph refresh...
2024-07-19T19:44:19.002949420 [I/Geode]: 19:44:19 INFO  [Thread #27570] [Geode]:   Took 0s
2024-07-19T19:44:19.003819171 [I/Geode]: 19:44:19 INFO  [Thread #27570] [Geode]: Latest version is v3.2.0
2024-07-19T19:44:19.021174802 [W/InteractionJankMonitor]: Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=com.geode.launcher
2024-07-19T19:44:19.022443642 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@fc230f8
2024-07-19T19:44:19.099101764 [I/ImeTracker]: com.geode.launcher:39798743: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
2024-07-19T19:44:20.647829629 [I/Geode]: 19:44:20 INFO  [Thread #27570] [Geode]: All mods up to date!
2024-07-19T19:44:22.008951456 [I/Geode]: 19:44:22 INFO  [Thread #27570] [Geode]: Saving mod data...
2024-07-19T19:44:22.017958495 [I/Geode]: 19:44:22 INFO  [Thread #27570] [Geode]:   Took 0.008s
2024-07-19T19:44:22.673788614 [I/Process]: Sending signal. PID: 27470 SIG: 9
2024-07-19T19:44:23.784505534 [I/.geode.launcher]: Using CollectorTypeCMC GC.
2024-07-19T19:44:23.787435140 [E/.geode.launcher]: Not starting debugger since process cannot load the jdwp agent.
2024-07-19T19:44:23.980235229 [W/Choreographer]: Frame time is 0.212303 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:24.058673055 [W/Choreographer]: Frame time is 0.317304 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:24.163553589 [W/Choreographer]: Frame time is 0.196743 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:44:25.452875814 [W/.geode.launcher]: Missing inline cache for boolean G.K.h(androidx.compose.ui.node.a)
2024-07-19T19:44:27.637026410 [W/.geode.launcher]: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
2024-07-19T19:44:27.637323244 [W/.geode.launcher]: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2024-07-19T19:44:27.637413047 [W/.geode.launcher]: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2024-07-19T19:44:27.679529258 [W/GeodeLauncher-fix]: failed to read symbol file at /storage/emulated/0/Android/media/com.geode.launcher/exception_symbols.txt
2024-07-19T19:44:27.708590781 [I/System.out]: Loading Geode from Geode.android64.so
2024-07-19T19:44:27.702 [W/.geode.launcher]: type=1400 audit(0.0:38611): avc:  granted  { execute } for  path="/data/data/com.geode.launcher/files/copied/Geode.so" dev="dm-51" ino=27873 scontext=u:r:untrusted_app:s0:c7,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c7,c257,c512,c768 tclass=file app=com.geode.launcher
2024-07-19T19:44:27.734893597 [I/Geode]: 19:44:27 INFO  [Main] [Geode]: Running Geode v3.2.0 in Geometry Dash v2.206 on Android64
2024-07-19T19:44:27.735032391 [I/Geode]: 19:44:27 INFO  [Main] [Geode]: Setting up internal mod
2024-07-19T19:44:27.744987958 [I/Geode]: 19:44:27 INFO  [Main] [Geode]: Setting up loader
2024-07-19T19:44:27.782385581 [I/Geode]: 19:44:27 INFO  [Main] [Geode]:   Refreshing mod graph
2024-07-19T19:44:27.783321169 [I/Geode]: 19:44:27 INFO  [Main] [Geode]:     Took 0s. Continuing next frame...
2024-07-19T19:44:27.783348024 [I/Geode]: 19:44:27 INFO  [Main] [Geode]: Starting loader update check
2024-07-19T19:44:27.783513145 [I/Geode]: 19:44:27 INFO  [Main] [Geode]: Entry took 0.048s
2024-07-19T19:44:27.836517417 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:27.836564333 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:27.836568483 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: OFF with frames = 0
2024-07-19T19:44:27.836571087 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:27.836573976 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:27.861170819 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
2024-07-19T19:44:27.999247479 [I/fmod]: FMOD::supportsLowLatency : Low latency = true, Pro Audio = true, Bluetooth On = false, Acceptable Block Size = true (128)
2024-07-19T19:44:27.999293500 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:27.999304689 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:27.999309450 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:44:27.999313478 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:27.999317751 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:28.019999717 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#2 ----------------
2024-07-19T19:44:28.143738812 [I/AAudio]: AAudioStreamBuilder_openStream() called ----------------------------------------
2024-07-19T19:44:28.143864707 [I/AudioStreamBuilder]: rate   =      0, channels  = 0, channelMask = 0, format   = 0, sharing = SH, dir = OUTPUT
2024-07-19T19:44:28.143887860 [I/AudioStreamBuilder]: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
2024-07-19T19:44:28.143904340 [I/AudioStreamBuilder]: usage  =     14, contentType = 0, inputPreset = 0, allowedCapturePolicy = 0
2024-07-19T19:44:28.143920412 [I/AudioStreamBuilder]: privacy sensitive = false, opPackageName = (null), attributionTag = (null)
2024-07-19T19:44:28.158176027 [I/AAudio]: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#3 ----------------
2024-07-19T19:44:28.209246584 [I/Geode]: 19:44:28 INFO  [Thread #27688] [Geode]: Continuing mod graph refresh...
2024-07-19T19:44:28.209389732 [I/Geode]: 19:44:28 INFO  [Thread #27688] [Geode]:   Took 0s
2024-07-19T19:44:28.210262209 [I/Geode]: 19:44:28 INFO  [Thread #27688] [Geode]: Latest version is v3.2.0
2024-07-19T19:44:28.229644289 [W/InteractionJankMonitor]: Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=com.geode.launcher
2024-07-19T19:44:28.234428998 [W/WindowOnBackDispatcher]: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@fc230f8
2024-07-19T19:44:28.301914919 [I/ImeTracker]: com.geode.launcher:3c1ef8aa: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
2024-07-19T19:44:29.961901329 [I/Geode]: 19:44:29 INFO  [Thread #27688] [Geode]: All mods up to date!
2024-07-19T19:44:34.888381801 [W/.geode.launcher]: Cleared Reference was only reachable from finalizer (only reported once)
2024-07-19T19:44:34.925608322 [I/.geode.launcher]: NativeAlloc concurrent mark compact GC freed 34MB AllocSpace bytes, 8(236KB) LOS objects, 85% free, 4011KB/27MB, paused 1.062ms,4.450ms total 106.329ms
2024-07-19T19:44:34.941389694 [W/System]: A resource failed to call close.
2024-07-19T19:44:34.941644089 [W/System]: A resource failed to call close.
2024-07-19T19:44:34.941899541 [E/System]: Uncaught exception thrown by finalizer
2024-07-19T19:44:34.942315557 [E/System]: java.io.IOException: close failed: EIO (I/O error)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:313)
	at java.io.FileInputStream.close(FileInputStream.java:578)
	at java.io.FileInputStream.finalize(FileInputStream.java:667)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:362)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:342)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:314)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: close failed: EIO (I/O error)
	at libcore.io.Linux.close(Native Method)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.BlockGuardOs.close(BlockGuardOs.java:113)
	at libcore.io.ForwardingOs.close(ForwardingOs.java:176)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:311)
	... 7 more
2024-07-19T19:44:34.942622930 [W/System]: A resource failed to call close.
2024-07-19T19:45:50.157634767 [W/Choreographer]: Frame time is 0.02601 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:45:54.644477380 [I/Geode]: 19:45:54 INFO  [Thread #27688] [Geode]: Saving mod data...
2024-07-19T19:45:54.652411258 [I/Geode]: 19:45:54 INFO  [Thread #27688] [Geode]:   Took 0.007s
2024-07-19T19:45:55.302923344 [I/Process]: Sending signal. PID: 27624 SIG: 9
2024-07-19T19:45:59.820460455 [I/.geode.launcher]: Using CollectorTypeCMC GC.
2024-07-19T19:45:59.825531460 [E/.geode.launcher]: Not starting debugger since process cannot load the jdwp agent.
2024-07-19T19:46:00.013218512 [W/Choreographer]: Frame time is 0.185913 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:46:00.091811163 [W/Choreographer]: Frame time is 0.199737 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:46:00.187821865 [W/Choreographer]: Frame time is 0.245689 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:46:01.707434618 [W/Choreographer]: Frame time is 0.116503 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:46:02.498721524 [W/.geode.launcher]: Missing inline cache for boolean G.K.h(androidx.compose.ui.node.a)
2024-07-19T19:46:04.606076384 [W/Choreographer]: Frame time is 0.171873 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2024-07-19T19:46:04.614788420 [W/Choreographer]: Frame time is 0.171315 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
```

We haven't been able to reproduce the freezing on nightly yet, but it's inconsistent, so it's hard to say if it's gone. The music issue persists, at any rate.

### Steps to Reproduce

Literally just playing the game I guess.

### Additional Information

Our setup is a bit unconventional, but We don't see how that would affect things. The phone runs CalyxOS, and the Geometry Dash apk(s) is pulled from a Google Play install on Our other phone.

The base game also desyncs audio really quickly, which is also something that happens with Geode (when there's audio at all). It feels faster on Geode, but that may be a perception thing.

**Comment by RayDeeUx** [comment]
> #### Geode Version
> 1.4.1

**Comment by RayDeeUx** [comment]
For reference, the current Geode version is 3.2.0.

**Comment by CrimsonFork** [comment]
Oh oops, that's the Geode Launcher version We looked up.

**Comment by CrimsonFork** [comment]
The actual version is indeed 3.2.0.
And uh… just found out that the audio only doesn't work if the game is launched with the clockwise rotation landscape mode. If the game is launched in the default, counter clockwise landscape, the audio works fine.

And now the desync issue doesn't happen at all, not sure what's up with that, but it wasn't being caused by Geode anyway.

**Comment by Fleeym** [comment]
Cleaning up old issues, closing.
