### ISSUE TITLE
Latest nightly crashes the game once opened

### ISSUE THREAD

**Issue by LNLenost** [geode-sdk/geode#1021]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

nightly-29dba46

### Steps to Reproduce

Opening the game

### Crash Report

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.geode.launcher/files/copied/Geode.so" has invalid shdr offset/size: 7333912/1600
	at java.lang.Runtime.load0(Runtime.java:933)
	at java.lang.System.load(System.java:1625)
	at com.geode.launcher.GeometryDashActivity.t(SourceFile:47)
	at com.geode.launcher.GeometryDashActivity.v(SourceFile:615)
	at com.geode.launcher.GeometryDashActivity.onCreate(SourceFile:172)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Activity.performCreate(Activity.java:8570)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by iNUCi** [comment]
why use nightly then

**Comment by LNLenost** [comment]
Yeah, just wanted to note it

**Comment by qimiko** [comment]
this usually means that the geode download got corrupted somehow 😕 just try deleting the geode.so file in the launcher and let it redownload

**Comment by LNLenost** [comment]
Ok, thx :)
