### ISSUE TITLE
Android: Game does not start

### ISSUE THREAD

**Issue by lightyyt** [geode-sdk/geode#586]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.21

### Steps to Reproduce

Unknown. 

### Crash Report

[Geode 2024-03-04 00.44.16.log](https://github.com/geode-sdk/geode/files/14475085/Geode.2024-03-04.00.44.16.log)
[Geode 2024-03-04 00.35.32.log](https://github.com/geode-sdk/geode/files/14475086/Geode.2024-03-04.00.35.32.log)
[Geode 2024-03-04 00.46.19.log](https://github.com/geode-sdk/geode/files/14475087/Geode.2024-03-04.00.46.19.log)
[Geode 2024-03-04 00.43.59.log](https://github.com/geode-sdk/geode/files/14475088/Geode.2024-03-04.00.43.59.log)

### Additional Information

If giving my Device info helps: ZTE Blade V10 Vita running Android 9

**Comment by zkayns** [comment]
my last dying wish on my deathbed... did you try installing geode for android 32 bit
![image](https://github.com/geode-sdk/geode/assets/80561998/28c87b98-60eb-4334-8ded-3ff662cf78ad)

**Comment by lightyyt** [comment]
I tried both just to be sure, but the 32bit one told me it wasnt compatible.

And i also did try other normal things like  reinstalling both apps or clearing the data of both apps

**Comment by qimiko** [comment]
weird, do you have a crash dump available?

also
> did you try installing geode for android 32 bit

 this is wrong. the game launched so atp it's not that

**Comment by lightyyt** [comment]
There doesnt seem to be any crash dump in my files.

**Comment by lightyyt** [comment]
Okay; More info: My Tablet, an Amazon Tab 10 Something with the Same Android Version works no problem with Geode... Is it an issue with my phone? Does it maybe have a protection against the method the loader uses?

**Comment by lightyyt** [comment]
One more info, when i go to the Application Logs, theres this error:
2024-03-05T06:53:59.369326673 [E/AndroidRuntime]: FATAL EXCEPTION: GLThread 465
Process: com.geode.launcher, PID: 7153
java.lang.RuntimeException: createContext failed: EGL_BAD_CONFIG
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1222)
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1213)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1063)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1429)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)


And this error:

[E] 2024-03-05T07:02:50.762022678

[.geode.launche]: Not starting debugger since process cannot load the jdwp agent.

**Comment by qimiko** [comment]
:exploding_head: ok that is a launcher bug, i will move the issue there. very odd, given that should be the same exact code that gd uses to select the config. will have to check some stuff
