### ISSUE TITLE
i cant launch geode :(

### ISSUE THREAD

**Issue by geometrydashpotato** [geode-sdk/geode#593]
### Geode Issue

- [X] I confirm that this crash is NOT related to a mod but directly to Geode Loader itself.

### Platform

Android64

### Geode Version

v2.0.0-beta.21

### Mods Installed

i cant launce geode using my bluestack 64:( 
im using pie 64 bit bluestacks
im using gd apk

error details:
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.robtopx.geometryjump-S99xoaTtjztKp2LTGIKDSw==/base.apk!/lib/arm64-v8a/libfmod.so" not found
	at java.lang.Runtime.load0(Runtime.java:947)
	at java.lang.System.load(System.java:1633)
	at com.geode.launcher.GeometryDashActivity.v(SourceFile:159)
	at com.geode.launcher.GeometryDashActivity.u(SourceFile:102)
	at com.geode.launcher.GeometryDashActivity.onCreate(SourceFile:93)
	at android.app.Activity.performCreate(Activity.java:7185)
	at android.app.Activity.performCreate(Activity.java:7176)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2929)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Steps to Reproduce

download bluestacks on pc
download gd apk
download geode
done

### Crash Report

java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/com.robtopx.geometryjump-S99xoaTtjztKp2LTGIKDSw==/base.apk!/lib/arm64-v8a/libfmod.so" not found
	at java.lang.Runtime.load0(Runtime.java:947)
	at java.lang.System.load(System.java:1633)
	at com.geode.launcher.GeometryDashActivity.v(SourceFile:159)
	at com.geode.launcher.GeometryDashActivity.u(SourceFile:102)
	at com.geode.launcher.GeometryDashActivity.onCreate(SourceFile:93)
	at android.app.Activity.performCreate(Activity.java:7185)
	at android.app.Activity.performCreate(Activity.java:7176)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1285)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2929)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by qimiko** [comment]
not a geode bug. you are using a 32bit version of the game, so you want to be using the version of the launcher labeled "32-bit"

**Comment by geometrydashpotato** [comment]
> not a geode bug. you are using a 32bit version of the game, so you want to be using the version of the launcher labeled "32-bit"

i downloaded both. its still not working :(
